Feature/8.x.x issue 799
OntimizeWeb/ontimize-web-ngx pull request #1000
Opened 2022-07-14 07:04 UTC by tomfacal

Closes #799.

2022-08-10 09:44 UTC, gonzalo-martinez-imt submitted a review, later dismissed

2022-08-12 05:33 UTC, patricia-martinez-imatia requested changes
After resizing a column and doing a reset, and if you resize that same column, the mouse jumps to the last previous resize point

![reset-width](https://user-images.githubusercontent.com/32088627/184290997-00d08ecb-6374-4dfc-ad39-f55e55e02f5d.gif)

2022-08-17 05:32 UTC, patricia-martinez-imatia requested changes
After resizing a column and clicking on reset the width of the columns, the resizing of the columns is correct but if you then want to resize a column again or it produces a jump to the previous point or it does not allow resizing the column 

![reset-width2](https://user-images.githubusercontent.com/32088627/185041857-57f30a13-d6b1-4bc6-9565-087af3a95cd4.gif)

2022-08-25 06:16 UTC, patricia-martinez-imatia approved these changes

2022-08-25 06:20 UTC, daniel-grana approved these changes

2022-08-25 06:21 UTC, merged