[8.x.x]Improve row grouping by date
OntimizeWeb/ontimize-web-ngx pull request #1036
Opened 2022-09-21 08:07 UTC by tomfacal

Closes #719.

2022-09-23 06:37 UTC, daniel-grana requested changes

2022-09-23 06:37 UTC, daniel-grana commented on projects/ontimize-web-ngx/src/lib/components/table/extensions/contextmenu/o-table-context-menu.component.ts
> +    this.isDateColumn.next(this.column.sqlType == 93);
This way is not fully correct. The types 91 or 92 are also relative to dates. We have to found another way of identifying date columns

2022-09-23 06:37 UTC, daniel-grana commented on projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
> +    if (attr.split('-')) {
It is necessary to find another way of identifying column and its group date operation. If the attr of the column contains hyphens this algorithm will fail.

2022-10-18 09:27 UTC, daniel-grana approved these changes

2022-10-18 09:31 UTC, patricia-martinez-imatia approved these changes

2022-10-18 09:33 UTC, merged