core fix buttons on dark mode
OntimizeWeb/ontimize-web-ngx pull request #1157
Opened 2023-02-06 10:55 UTC by javierFernandezMendez

2023-02-06 14:09 UTC, daniel-grana submitted a review, later dismissed

2023-02-06 14:27 UTC, patricia-martinez-imatia approved these changes

2023-02-06 14:31 UTC, patricia-martinez-imatia requested changes

2023-02-06 14:31 UTC, patricia-martinez-imatia commented on projects/ontimize-web-ngx/src/lib/components/theming/app-global-theme.scss
> +          color: mat-color($primary, 800);
```suggestion
          color: mat-color($accent, 800);
```

2023-02-08 08:06 UTC, daniel-grana approved these changes

2023-02-08 11:04 UTC, patricia-martinez-imatia approved these changes

2023-02-08 11:15 UTC, daniel-grana approved these changes

2023-02-08 11:15 UTC, merged