Sync release 15.0.3 to develop
OntimizeWeb/ontimize-web-ngx pull request #1533
Opened 2024-03-18 10:03 UTC by ontimize-web

Automated pull request for synchronizing released version (15.0.3) into develop branch

### 💡 Merge Strategy: Create a merge commit

2024-03-18 10:04 UTC, daniel-grana approved these changes

2024-03-18 11:58 UTC, daniel-grana requested changes
Solve conflicts

2024-03-20 08:04 UTC, tomfacal approved these changes

2024-03-20 08:11 UTC, daniel-grana approved these changes

2024-03-20 08:11 UTC, merged