[8.x.x] Improvements in filtering by columns
OntimizeWeb/ontimize-web-ngx pull request #423
Opened 2020-09-02 09:29 UTC by patricia-martinez-imatia

- Added button to sort the rendered values in the dialog
- Added sort_by_alpha,sort_by_alpha_add and sort_by_alpha_desc in ontimize icons
- Added clear button  in custom filter

2020-09-02 10:25 UTC, manuel-cid requested changes

2020-09-02 10:25 UTC, manuel-cid commented on CHANGELOG.md
> +* **icons**: Added sort_by_alpha,sort_by_alpha_add and sort_by_alpha_desc icons in Ontimize Web ([edd8927](https://github.com/OntimizeWeb/ontimize-web-ngx/commit/edd8927))
Fix icon reference name `sort_by_alpha_add` to `sort_by_alpha_asc`

2020-09-02 10:25 UTC, manuel-cid commented on projects/ontimize-web-ngx/src/lib/components/table/extensions/dialog/filter-by-column/o-table-filter-by-column-data-dialog.component.ts
> +      case '':
Use switch `default` option instead of `case ''`

2020-09-02 10:25 UTC, manuel-cid commented on projects/ontimize-web-ngx/src/lib/components/table/extensions/dialog/filter-by-column/o-table-filter-by-column-data-dialog.component.ts
> +    //sortFunction(propertyA: any, propertyB: any): number {
Remove commented code

2020-09-02 12:01 UTC, manuel-cid approved these changes

2020-09-02 12:02 UTC, pacogomezimatia approved these changes

2020-09-10 10:25 UTC, daniel-grana approved these changes

2020-09-10 11:10 UTC, merged