[4.x.x] Improvements in filtering by columns
OntimizeWeb/ontimize-web-ngx pull request #425
Opened 2020-09-02 12:17 UTC by patricia-martinez-imatia

- Added button to sort the rendered values in the dialog
- Added sort_by_alpha,sort_by_alpha_asc and sort_by_alpha_desc in ontimize icons
- Added clear button in custom filter

2020-09-03 06:32 UTC, manuel-cid requested changes

2020-09-03 06:32 UTC, manuel-cid commented on CHANGELOG.md
> +## 4.1.3 (2020-07-14)
Version 4.1.3 has been released on 2020-08-18

2020-09-07 10:20 UTC, manuel-cid approved these changes

2020-09-07 12:55 UTC, pacogomezimatia approved these changes

2020-09-10 08:44 UTC, daniel-grana approved these changes

2020-09-10 11:15 UTC, merged