Import o-table-buttons-component in table-component not the interface
OntimizeWeb/ontimize-web-ngx pull request #446
Opened 2020-10-13 13:49 UTC by pacogomezimatia

2020-10-16 09:21 UTC, daniel-grana requested changes

2020-10-16 09:21 UTC, daniel-grana commented on projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
> +  // @ViewChild('tableButtons', { static: false })
Please remove this statement if it is not necessary

2020-10-16 09:37 UTC, daniel-grana approved these changes

2020-10-21 06:44 UTC, manuel-cid approved these changes

2020-10-21 06:48 UTC, patricia-martinez-imatia approved these changes

2020-10-22 06:42 UTC, gonzalo-martinez-imt approved these changes

2020-10-22 13:57 UTC, merged