[8.x.x]New `toolbar-color`  attribute in o-app-layout component
OntimizeWeb/ontimize-web-ngx pull request #496
Opened 2021-01-28 14:54 UTC by patricia-martinez-imatia

2021-01-28 15:02 UTC, daniel-grana approved these changes

2021-01-28 16:12 UTC, pacogomezimatia approved these changes

2021-01-29 08:28 UTC, manuel-cid commented on projects/ontimize-web-ngx/src/lib/components/app-header/o-app-header.component.html
> +<nav fxFlex fxLayout="row" fxLayoutAlign="space-between stretch" [ngClass]="getColorClass()">
Maybe it is better to use something like this
`[ngClass]="color ? 'o-app-header-'+color : ''"`
So we avoid method `getColorClass` will be executed all the time.

2021-01-29 08:29 UTC, manuel-cid requested changes
LGTM

2021-02-01 08:08 UTC, gonzalo-martinez-imt approved these changes

2021-02-01 14:03 UTC, merged