Fix collapsible containers internal scroll
OntimizeWeb/ontimize-web-ngx pull request #510
Opened 2021-02-10 14:40 UTC by manuel-cid

2021-02-17 07:50 UTC, pacogomezimatia approved these changes

2021-02-17 10:20 UTC, daniel-grana requested changes

2021-02-17 10:20 UTC, daniel-grana commented on ontimize/components/container/o-container-collapsible-component.class.ts
> +    // this.updateOutlineGap();
Please remove commented code if it is not necessary anymore

2021-02-17 11:31 UTC, daniel-grana approved these changes

2021-02-18 06:00 UTC, patricia-martinez-imatia approved these changes

2021-02-18 08:22 UTC, merged