[8.x.x] Pagination Size Option input added
OntimizeWeb/ontimize-web-ngx pull request #512
Opened 2021-02-11 13:32 UTC by pacogomezimatia

2021-02-11 14:30 UTC, manuel-cid approved these changes

2021-02-11 14:42 UTC, gonzalo-martinez-imt approved these changes

2021-02-11 14:48 UTC, daniel-grana requested changes

2021-02-11 14:48 UTC, daniel-grana commented on projects/ontimize-web-ngx/src/lib/components/table/extensions/footer/paginator/o-base-table-paginator.class.ts
> +      this._pageSizeOptions = JSON.parse(value)
Protect this code, if the parse fails it would be great to assign default values

2021-02-18 06:02 UTC, patricia-martinez-imatia approved these changes

2021-02-23 12:05 UTC, merged