[8.x.x] Improvements combo
OntimizeWeb/ontimize-web-ngx pull request #515
Opened 2021-02-19 10:39 UTC by patricia-martinez-imatia

Fixed in multiple combo
- SetValue doesnt work
- SetSelectedItems doesnt work
- If data is null and you put multiple-trigger-label = true the component  doesnt work

2021-02-19 11:07 UTC, daniel-grana requested changes

2021-02-19 11:07 UTC, daniel-grana commented on projects/ontimize-web-ngx/src/lib/components/input/combo/o-combo.component.html
> +        <span *ngIf="getFormControl().value && getFormControl().value.length > 1">
We should protect this, it may happen that getFormControl().value is undefined

2021-02-19 15:12 UTC, daniel-grana approved these changes

2021-02-23 09:09 UTC, manuel-cid approved these changes

2021-02-23 12:05 UTC, pacogomezimatia approved these changes

2021-02-24 06:09 UTC, merged