[8.x.x] Issue #513
OntimizeWeb/ontimize-web-ngx pull request #525
Opened 2021-02-24 13:13 UTC by gonzalo-martinez-imt

2021-02-24 14:12 UTC, daniel-grana approved these changes

2021-02-24 16:55 UTC, manuel-cid requested changes

2021-02-24 16:55 UTC, manuel-cid commented on projects/ontimize-web-ngx/src/lib/components/input/percent-input/o-percent-input.component.ts
> +      this.min = 0; this.min = 0;
Same instruction twice, why?

2021-02-24 16:55 UTC, manuel-cid commented on projects/ontimize-web-ngx/src/lib/components/input/percent-input/o-percent-input.component.ts
> +      this.max = 100; this.max = 100;
Same instruction twice, why?

2021-02-25 07:05 UTC, patricia-martinez-imatia approved these changes

2021-02-25 10:14 UTC, pacogomezimatia approved these changes

2021-02-25 10:27 UTC, merged