New pattern validator
OntimizeWeb/ontimize-web-ngx pull request #539
Opened 2021-03-04 14:49 UTC by patricia-martinez-imatia

New pattern validator

2021-03-04 14:55 UTC, daniel-grana requested changes

2021-03-04 14:55 UTC, daniel-grana commented on projects/ontimize-web-ngx/src/lib/validators/o-validators.ts
> +      const valid = regex.test(control.value);
Maybe it would be necessary to check that _regex_ arg is not undefined for avoiding exceptions

2021-03-05 09:54 UTC, daniel-grana approved these changes

2021-03-08 09:00 UTC, pacogomezimatia approved these changes

2021-03-08 10:46 UTC, gonzalo-martinez-imt approved these changes

2021-03-08 11:01 UTC, manuel-cid approved these changes

2021-03-08 11:44 UTC, merged