[8.x.x] Custom render for o-combo and o-listpicker
OntimizeWeb/ontimize-web-ngx pull request #540
Opened 2021-03-04 15:24 UTC by pacogomezimatia

2021-03-10 11:43 UTC, daniel-grana approved these changes

2021-03-11 16:32 UTC, manuel-cid requested changes

2021-03-11 16:32 UTC, manuel-cid commented on projects/ontimize-web-ngx/src/lib/components/input/combo/combo-renderer/o-combo-renderer.class.ts
> +  }
Do we need this empty method?

2021-03-11 16:32 UTC, manuel-cid commented on projects/ontimize-web-ngx/src/lib/components/input/listpicker/listpicker-renderer/o-listpicker-renderer.class.ts
> +  }
Do we need this empty method?

2021-03-12 09:06 UTC, manuel-cid approved these changes

2021-03-15 08:13 UTC, patricia-martinez-imatia approved these changes

2021-03-17 11:12 UTC, pacogomezimatia commented
#547

2021-03-17 11:12 UTC, closed without merging