[8.x.x] Form layout manager new split-pane mode and refactor
OntimizeWeb/ontimize-web-ngx pull request #558
Opened 2021-04-08 07:55 UTC by gonzalo-martinez-imt

2021-05-19 14:00 UTC, daniel-grana requested changes

2021-05-19 14:00 UTC, daniel-grana commented on package.json
> +    "angular-resizable-element": "3.3.4"
I think that it is useful to maintain the libraries odered alfabetically

2021-05-19 14:00 UTC, daniel-grana commented on projects/ontimize-web-ngx/ng-package.json
> +      "angular-resizable-element": "angularResizableElement"
The same as previous commment

2021-05-19 14:00 UTC, daniel-grana commented on projects/ontimize-web-ngx/ng-package.json
> +    "angular-resizable-element"
The same as previous commment

2021-05-19 14:00 UTC, daniel-grana commented on projects/ontimize-web-ngx/package.json
> +    "angular-resizable-element": "3.3.4"
The same as previous commment

2021-05-20 07:27 UTC, manuel-cid requested changes

2021-05-20 07:27 UTC, manuel-cid commented on projects/ontimize-web-ngx/src/lib/layouts/form-layout/split-pane/o-form-layout-split-pane.component.html
> +<div fxFill>
Is this `div` needed? Can we move the `fxFill` to the next `div` that already has `height: 100%` in the class `row-wrapper`

2021-05-20 07:27 UTC, manuel-cid commented on projects/ontimize-web-ngx/src/lib/layouts/form-layout/split-pane/o-form-layout-split-pane.component.html
> +      <div class="secondary-content" fxLayout="column" fxLayoutAlign="center stretch" fxFlex>
Can we rename css classes to something that starts with `o-` and makes reference to the current component?

2021-05-20 08:31 UTC, gonzalo-martinez-imt commented on projects/ontimize-web-ngx/src/lib/components/form/navigation/o-form-navigation.component.ts
> +  private moveInFormLayoutManager(formLayoutManager: OFormLayoutManagerComponent, index: number) {
You are right, besides of that we would also have the reference to the formLayoutManager in the compnent using this.formLayoutManager. Thank you

2021-05-20 13:31 UTC, manuel-cid submitted a review, later dismissed

2021-05-21 15:10 UTC, daniel-grana approved these changes

2021-05-27 13:32 UTC, manuel-cid approved these changes

2021-05-27 13:33 UTC, pacogomezimatia approved these changes

2021-05-27 13:34 UTC, merged