[8.x.x] New input for o-table visible-columns-by-default
OntimizeWeb/ontimize-web-ngx pull request #648
Opened 2021-06-22 10:21 UTC by pacogomezimatia

2021-06-22 13:17 UTC, manuel-cid approved these changes

2021-06-22 15:59 UTC, daniel-grana requested changes

2021-06-22 15:59 UTC, daniel-grana commented on projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
> +  'visibleColumnsByDefault: visible-columns-by-default',
Rename to defaultVisibleColumns: default-visible-columns

2021-06-23 08:54 UTC, daniel-grana approved these changes

2021-06-23 08:55 UTC, merged