[8.x.x] Row grouping: collapsing row groups makes columns aggregate have a wrong value
OntimizeWeb/ontimize-web-ngx pull request #750
Opened 2021-09-14 11:29 UTC by patricia-martinez-imatia

Updated sum, count, avg, max and min operations when data is grouped

2021-09-14 12:04 UTC, gonzalo-martinez-imt requested changes

2021-09-15 12:20 UTC, patricia-martinez-imatia commented on projects/ontimize-web-ngx/src/lib/components/table/extensions/default-o-table.datasource.ts
> +  isParentTableGroupRow(tableRowGroup: any) {
isParentTableGroupRow method amended by **isFirstLevelTableGroupRow**

2021-09-16 11:47 UTC, manuel-cid approved these changes

2021-09-17 06:59 UTC, gonzalo-martinez-imt approved these changes

2021-09-20 08:08 UTC, merged