[8.x.x] Row grouping: align aggregation title depending on column type
OntimizeWeb/ontimize-web-ngx pull request #763
Opened 2021-09-24 10:09 UTC by patricia-martinez-imatia

Alignment on aggregate column heading with same default column type alignment

2021-09-24 11:43 UTC, gonzalo-martinez-imt approved these changes

2021-09-24 13:15 UTC, daniel-grana requested changes

2021-09-24 13:15 UTC, daniel-grana commented on projects/ontimize-web-ngx/src/lib/components/table/o-table.component.ts
> +  public getGroupHeadeCellAlignClass(column: string): string[] {
```suggestion
  public getGroupHeaderCellAlignClass(column: string): string[] {
```
Fix typo in method name

2021-09-24 13:38 UTC, daniel-grana approved these changes

2021-09-24 13:45 UTC, daniel-grana approved these changes

2021-09-27 06:32 UTC, pacogomezimatia approved these changes

2021-09-27 06:58 UTC, gonzalo-martinez-imt approved these changes

2021-09-27 06:59 UTC, merged