[8.5.2] insertable row reusing cell-editor bug
OntimizeWeb/ontimize-web-ngx pull request #792
Opened 2021-10-05 16:12 UTC by gonzalo-martinez-imt

Closes #790

2021-10-05 16:32 UTC, daniel-grana requested changes

2021-10-05 16:32 UTC, daniel-grana commented on CHANGELOG.md
> +## 8.5.1
```suggestion
## 8.5.2 
```

2021-10-06 08:05 UTC, daniel-grana approved these changes

2021-10-06 08:18 UTC, pacogomezimatia approved these changes

2021-10-06 08:29 UTC, merged