[8.x.x] Pagination for o-list
OntimizeWeb/ontimize-web-ngx pull request #927
Opened 2022-03-24 14:49 UTC by patricia-martinez-imatia

- Added `page-size-options` and `pagination-controls` inputs  in DEFAULT_INPUTS_O_SERVICE_COMPONENT array and removed  `page-size-options` and `pagination-controls` in o-table and o-grid
- Moved  `onChangePage` and `getPaginationDataFromArray` method in o-grid.component.s to o-service-component.class.ts
- Added `mat-paginator` in **o-list** component

2022-03-24 15:37 UTC, daniel-grana requested changes

2022-03-24 15:37 UTC, daniel-grana commented on CHANGELOG.md
> +  * **o-list**: added pagination ([4cdb80c](https://github.com/OntimizeWeb/ontimize-web-ngx/commit/4cdb80c)) Closes [#861](https://github.com/OntimizeWeb/ontimize-web-ngx/issues/861)
Add more clearer comment, specifying what is added is the component of pagination with page selector, etc. Right now, pagination already exists in list

2022-03-24 15:37 UTC, daniel-grana commented on projects/ontimize-web-ngx/src/lib/components/o-service-component.class.ts
> +  public onChangePage(e: PageEvent): void {
Sonar is pointing that this method is duplicated on o-grid.component.ts. Please check it out

2022-03-25 14:41 UTC, daniel-grana approved these changes

2022-03-29 07:07 UTC, gonzalo-martinez-imt approved these changes

2022-03-29 08:05 UTC, merged