[8.x.x] Updated exportData method
OntimizeWeb/ontimize-web-ngx pull request #998
Opened 2022-07-13 08:14 UTC by patricia-martinez-imatia

Adapt exportData method  to new backend service

2022-10-21 14:30 UTC, daniel-grana requested changes

2022-10-21 14:30 UTC, daniel-grana commented on projects/ontimize-web-ngx/src/lib/interfaces/o-table-export-data.interface.ts
> +export interface OTableExcelExportData3X extends OTableExportData3X {
Change this interface name by a generic one due to it is also used into PDF export operation

2022-10-21 14:30 UTC, daniel-grana commented on projects/ontimize-web-ngx/src/lib/types/query-parameter.type.ts
> +export type QueryParameter = {
If we want keep concordance with backend. the `QueryParameter` only has the attributes: filter, columns and sqltypes.
The `AdvancedQueryParameter` adds the attributes: offset, pageSize and orderBy

2022-10-21 14:30 UTC, daniel-grana commented on projects/ontimize-web-ngx/src/lib/services/ontimize/ontimize-export.service.ts
> +  public exportData(format: string): Observable<any> {
It is a **breaking change** isn't it? Maybe someone overrides this service method and it will not work anymore.

2022-10-25 11:08 UTC, tomfacal submitted a review, later dismissed

2022-10-25 11:23 UTC, daniel-grana approved these changes

2022-10-25 11:42 UTC, tomfacal approved these changes

2022-10-25 13:29 UTC, merged